version: '3'

volumes:
  sqlserver:
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    volumes:
      - sqlserver:/var/opt/mssql
    mem_limit: 1g
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
      MSSQL_PID: "Express"

    ports:
      - "1433:1433"
